# This is a basic workflow to help you get started with Actions

name: PR_unit_tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['centos:7']
      fail-fast: false

#    container:
#      image: ${{ matrix.container-version }}
#      options: --user 1001
#      strategy:
#        matrix:
#          container-version: ['centos:7']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: cat /etc/os-release

      # Runs a single command using the runners shell
      - name: install required packages
        run: |
          yum install -y gcc python3 python3-devel python3-pip krb5-workstation krb5-devel

      - name: install pip virtualenv and tox
        run: pip3 install virtualenv tox

      - name: create and set new user
        run: |
             sudo useradd teflo_user
             su teflo_user

      # Runs a set of commands using the runners shell
      - name: Run functional unit tests
        env:
          LC_ALL: en_US.utf8
          LANG: en_US.utf8
        run: tox -e py3-unit

      # Runs a set of commands using the runners shell
      - name: Run local scenario unit test
        env:
          LC_ALL: en_US.utf8
          LANG: en_US.utf8
        run: tox -e py3-scenario
